/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_esciencecenter_ncradar_RadarScan */

#ifndef _Included_nl_esciencecenter_ncradar_RadarScan
#define _Included_nl_esciencecenter_ncradar_RadarScan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_esciencecenter_ncradar_RadarScan
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_nl_esciencecenter_ncradar_RadarScan_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
